pawon-backend/src/main/java/org/dailycode/pawon/backend/controller/GalleriaListController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.dailycode.pawon.backend.controller;

import java.io.IOException;
import java.io.Serializable;
import org.dailycode.pawon.backend.AppBackend;
import org.dailycode.pawon.backend.listener.ActionListListener;
import org.dailycode.pawon.core.entity.Galleria;
import org.dailycode.pawon.datamodel.GalleriaSelectableDataModel;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 *
 * @author kris
 */
@Controller("galleriaList")
@Scope("view")
public class GalleriaListController extends BaseController implements ActionListListener, Serializable {

    private Galleria selectedGalleria;
    private GalleriaSelectableDataModel galleriaSelectableDataModel;

    @Override
    public void init() {
        galleriaSelectableDataModel = new GalleriaSelectableDataModel(getService().getGalleriaService().getAll(false));
    }

    @Override
    public void actionForm() throws IOException {
        redirectView("galleria_form", AppBackend.SN_ENTITY, true);
    }

    @Override
    public void actionEdit() throws IOException {
        if (selectedGalleria != null) {
            redirectView("galleria_form", AppBackend.SN_ENTITY, selectedGalleria);
        } else {
            showMessageEditEmpty();
        }
    }

    @Override
    public void actionDelete() throws IOException {
        if (selectedGalleria != null) {
            getService().getUserService().delete(selectedGalleria.getId());
            redirectView("galleria_form", AppBackend.SN_ENTITY, null);
        } else {
            showMessageDeleteEmpty();
        }
    }

    @Override
    public void actionSearch() throws IOException {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Galleria getSelectedPromo() {
        return selectedGalleria;
    }

    public void setSelectedPromo(Galleria selectedPromo) {
        this.selectedGalleria = selectedPromo;
    }

    public GalleriaSelectableDataModel getGalleriaSelectableDataModel() {
        return galleriaSelectableDataModel;
    }

    public void setGalleriaSelectableDataModel(GalleriaSelectableDataModel galleriaSelectableDataModel) {
        this.galleriaSelectableDataModel = galleriaSelectableDataModel;
    }
}

pawon-backend/src/main/java/org/dailycode/pawon/backend/controller/ItemCategoryListController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.dailycode.pawon.backend.controller;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import org.dailycode.pawon.backend.AppBackend;
import org.dailycode.pawon.backend.listener.ActionListListener;
import org.dailycode.pawon.core.common.Section;
import org.dailycode.pawon.core.entity.Item;
import org.dailycode.pawon.core.entity.ItemCategory;
import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 *
 * @author Kris Sadewo
 * @date Feb 8, 2013
 */
@Controller("itemCategoryList")
@Scope("view")
public class ItemCategoryListController extends BaseController implements ActionListListener, Serializable {

    private TreeNode selectedNode;
    private ItemCategory selectedItemCategory;
    private String searchCodeKey;
    private String searchNameKey;
    private String searchCategoryKey;
    private TreeNode root;
    private Section section;
    private List<String> sections = new ArrayList<>();
    List<Item> items = new ArrayList<>();

    @Override
    public void init() {
        sections = createdSections();
        section = getCurrentSection();
        if (section == null) {
            section = Section.RESTAURANT;
        }
        changeSelectedSection();
    }

    private void createTree() {
        root = new DefaultTreeNode("root", null);
        for (ItemCategory itemCategory : getService().getItemCategoryService().getBySection(section)) {
            if (itemCategory.getParentId() == 0) {
                createTree(itemCategory, root);
            }
        }
    }

    private TreeNode createTree(ItemCategory itemCategory, TreeNode rootNode) {
        TreeNode parentNode = new DefaultTreeNode(itemCategory, rootNode);
        parentNode.setExpanded(true);

        for (ItemCategory parent : getService().getItemCategoryService().getByParent(itemCategory.getId())) {
            TreeNode childNode = createTree(parent, parentNode);
            childNode.setExpanded(true);
        }
        return parentNode;
    }

    public TreeNode getRoot() {
        return root;
    }

    @Override
    public void actionForm() {
        redirectView("category_form", AppBackend.SN_ENTITY, true);
    }

    @Override
    public void actionEdit() throws IOException {
        if (selectedNode != null) {
            redirectView("category_form", AppBackend.SN_ENTITY,
                    getService().getItemCategoryService().getById(((ItemCategory) selectedNode.getData()).getId()));
        } else {
            showMessageEditEmpty();
        }
    }

    @Override
    public void actionDelete() throws IOException {
        if (selectedNode != null) {
            getService().getItemCategoryService().delete(((ItemCategory) selectedNode.getData()).getId());
            changeSelectedSection();           
        } else {
            showMessageDeleteEmpty();
        }
    }

    @Override
    public void actionSearch() throws IOException {
       
    }

    public void changeSelectedSection() {
        AppBackend.getInstance().setSessionMapValue(AppBackend.SN_SECTION, section);
        createTree();
    }

    public Section getPurchaseSection() {
        return section;
    }

    public void setPurchaseSection(Section purchaseSection) {
        this.section = purchaseSection;
    }

    public List<String> getPurchaseSections() {
        return sections;
    }

    public TreeNode getSelectedNode() {
        return selectedNode;
    }

    public void setSelectedNode(TreeNode selectedNode) {
        this.selectedNode = selectedNode;
    }

    public String getSearchCodeKey() {
        return searchCodeKey;
    }

    public void setSearchCodeKey(String searchCodeKey) {
        this.searchCodeKey = searchCodeKey;
    }

    public String getSearchNameKey() {
        return searchNameKey;
    }

    public void setSearchNameKey(String searchNameKey) {
        this.searchNameKey = searchNameKey;
    }

    public String getSearchCategoryKey() {
        return searchCategoryKey;
    }

    public void setSearchCategoryKey(String searchCategoryKey) {
        this.searchCategoryKey = searchCategoryKey;
    }

    public ItemCategory getSelectedItemCategory() {
        return selectedItemCategory;
    }

    public void setSelectedItemCategory(ItemCategory selectedItemCategory) {
        items = getService().getItemService().getByCategory(selectedItemCategory.getId());
        this.selectedItemCategory = selectedItemCategory;
    }

    public List<Item> getItems() {
        return items;
    }

    public void setItems(List<Item> items) {
        this.items = items;
    }
}

pawon-backend/src/main/java/org/dailycode/pawon/backend/controller/ItemOptionFormController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.dailycode.pawon.backend.controller;

import org.dailycode.pawon.backend.AppBackend;
import org.dailycode.pawon.backend.listener.ActionFormListener;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.faces.component.html.HtmlInputText;
import javax.faces.component.html.HtmlOutputText;
import javax.faces.event.PhaseId;
import org.dailycode.pawon.core.common.Section;
import org.dailycode.pawon.core.entity.ItemOption;
import org.dailycode.pawon.core.entity.Language;
import org.dailycode.pawon.core.entity.LocalizedInformation;
import org.primefaces.component.editor.Editor;
import org.primefaces.component.panelgrid.PanelGrid;
import org.primefaces.component.tabview.Tab;
import org.primefaces.component.tabview.TabView;
import org.primefaces.event.NodeSelectEvent;
import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 *
 * @author kris
 * @created Mar 7, 2013
 */
@Controller("itemOptionForm")
@Scope("view")
public class ItemOptionFormController extends BaseController implements ActionFormListener, Serializable {

    private ItemOption itemOption;
    private ItemOption parentItemOption;
    private TabView tabView;
    private TreeNode root;
    private TreeNode selectedNode;
    private HtmlInputText inputTextTitle;
    private HtmlOutputText outputTextTitle;
    private Editor editor;
    private List<Language> languages = new ArrayList<>();
    private Long currentParentOptionId;
    private Section purchaseSection;

    @Override
    public void init() {
        languages = getService().getLanguageService().getActiveLanguage();
        purchaseSection = getCurrentSection();

        //Set default item option
        itemOption = (ItemOption) getCurrentEntity();
        if (itemOption == null) {
            itemOption = new ItemOption();
            itemOption.setOrderNumber(1);
        } else {
            parentItemOption = getService().getItemOptionService().getById(itemOption.getParentId());
        }

        currentParentOptionId = itemOption.getParentId();

        createDynamicTabView();

        if (getFacesContext().getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
            createTree();
        }
    }

    private void createTree() {
        root = new DefaultTreeNode("root", null);

        List<ItemOption> itemOptions = getService().getItemOptionService().getByPurchaseSection(purchaseSection);
        for (ItemOption ic : itemOptions) {
            if (ic.getParentId() == 0) {
                createTree(ic, root);
            }
        }
    }

    private TreeNode createTree(ItemOption pItemOption, TreeNode rootNode) {
        TreeNode parentNode = new DefaultTreeNode(pItemOption, rootNode);

        for (ItemOption parent : getService().getItemOptionService().getByParent(pItemOption.getId())) {
            TreeNode childNode = createTree(parent, parentNode);
            childNode.setSelectable(false);

            if (parent.getParentId() == currentParentOptionId) {
                parentNode.setSelected(true);
                parentNode.setExpanded(true);
                childNode.setExpanded(true);
            }
        }
        return parentNode;
    }

    private void createDynamicTabView() {
        // tabView = (TabView) FacesContext.getCurrentInstance().getViewRoot().findComponent("form:tabView");
        tabView = new TabView();
        for (Language language : languages) {
            LocalizedInformation information = getService().getLocalizedInformationService().getByItemOptionAndLanguage(itemOption, language);

            Tab tab = new Tab();
            tab.setId("tab" + language.getId());
            tab.setTitle(language.getName());

            outputTextTitle = new HtmlOutputText();
            outputTextTitle.setId("output" + language.getId());
            outputTextTitle.setValue("Title :");

            inputTextTitle = new HtmlInputText();
            inputTextTitle.setId("inputTextTitle" + language.getId());
            inputTextTitle.setStyle("width:50%");

            editor = new Editor();
            editor.setId("editor" + language.getId());
            editor.setWidth(700);

            if (information != null) {
                inputTextTitle.setValue(information.getTitle());
                editor.setValue(information.getDescription());
            }

            PanelGrid panelGrid = new PanelGrid();
            panelGrid.setId("grid" + language.getId());
            panelGrid.setStyle("border-style: hidden !important;");
            panelGrid.setColumns(1);
            panelGrid.getChildren().add(outputTextTitle);
            panelGrid.getChildren().add(inputTextTitle);
            panelGrid.getChildren().add(editor);

            tab.getChildren().add(panelGrid);

            tabView.getChildren().add(tab);
        }
    }

    public void onNodeSelect(NodeSelectEvent event) {
        parentItemOption = (ItemOption) selectedNode.getData();
        if (parentItemOption.getId() != currentParentOptionId) {
            itemOption.setOrderNumber(suggestOrderNumber(getService().getItemOptionService().getByParentAndPurchaseSection(parentItemOption.getId(), purchaseSection)));
        } else {
            itemOption.setOrderNumber(getService().getItemOptionService().getById(itemOption.getId()).getOrderNumber());
        }
    }

    private int suggestOrderNumber(List<ItemOption> options) {
        if (options.isEmpty()) {
            return 1;
        }
        return options.size() + 1;
    }

    @Override
    public void actionCancel() throws IOException {
        redirectView("option_list", AppBackend.SN_ENTITY, true);
    }

    @Override
    public void actionSave() throws IOException {
        itemOption.setSection(purchaseSection);

        for (Language language : languages) {
            inputTextTitle = (HtmlInputText) getFacesContext().getViewRoot().findComponent("form:tabView:inputTextTitle" + language.getId());
            editor = (Editor) getFacesContext().getViewRoot().findComponent("form:tabView:editor" + language.getId());

            LocalizedInformation localizedInformation = getService().getLocalizedInformationService().getByItemOptionAndLanguage(itemOption, language);
            if (localizedInformation == null) {
                localizedInformation = new LocalizedInformation();
            }

            if (inputTextTitle.getValue() != null) {
                localizedInformation.setTitle(inputTextTitle.getValue().toString());
            }

            if (editor.getValue() != null) {
                localizedInformation.setDescription(editor.getValue().toString());
            }

            localizedInformation.setItemOption(itemOption);
            localizedInformation.setLanguage(language);
            itemOption.getLocalizedInformations().add(localizedInformation);
        }

        if (parentItemOption != null) {
            itemOption.setParentId(parentItemOption.getId());
        }

        if (getService().getItemOptionService().saveOrUpdate(itemOption) != null) {
            redirectView("option_list", AppBackend.SN_ENTITY, true);
        } else {
            redirectView(DB_ERROR_VIEW, AppBackend.SN_ENTITY, true);
        }
    }

    public ItemOption getItemOption() {
        return itemOption;
    }

    public void setItemOption(ItemOption itemOption) {
        this.itemOption = itemOption;
    }

    public TreeNode getRoot() {
        return root;
    }

    public void setRoot(TreeNode root) {
        this.root = root;
    }

    public TreeNode getSelectedNode() {
        for (int i = 0; i < root.getChildren().size(); i++) {
            removeDefaultSelectedTree(root.getChildren().get(i));
        }
        return selectedNode;
    }

    public void setSelectedNode(TreeNode selectedNode) {
        this.selectedNode = selectedNode;
    }

    public List<Language> getLanguages() {
        return languages;
    }

    public void setLanguages(List<Language> languages) {
        this.languages = languages;
    }

    public TabView getTabView() {
        return tabView;
    }

    public void setTabView(TabView tabView) {
        this.tabView = tabView;
    }

    public ItemOption getParentItemOption() {
        return parentItemOption;
    }

    public void setParentItemOption(ItemOption parentItemOption) {
        this.parentItemOption = parentItemOption;
    }

    public ItemOption getCurrentItemOption() {
        return getService().getItemOptionService().getOrganizedParent(purchaseSection, itemOption, true);
    }
}

pawon-backend/src/main/java/org/dailycode/pawon/backend/controller/SystemParameterController.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.dailycode.pawon.backend.controller;

import java.io.IOException;
import java.io.Serializable;
import org.dailycode.pawon.backend.listener.ActionFormListener;
import org.dailycode.pawon.core.entity.SystemParameter;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

/**
 *
 * @author kris
 */
@Controller("systemParameterForm")
@Scope("view")
public class SystemParameterController extends BaseController implements ActionFormListener, Serializable {

    private SystemParameter systemParameter;

    @Override
    public void init() {
        systemParameter = getService().getSystemParameterService().getAll().get(0);
    }

    @Override
    public void actionCancel() throws IOException {
    }

    @Override
    public void actionSave() throws IOException {
        getService().getSystemParameterService().saveOrUpdate(systemParameter);
    }

    public SystemParameter getSystemParameter() {
        return systemParameter;
    }

    public void setSystemParameter(SystemParameter systemParameter) {
        this.systemParameter = systemParameter;
    }
}

pawon-backend/src/main/webapp/ui/master/category_list.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:c="http://java.sun.com/jsp/jstl/core"
                xmlns:fn="http://java.sun.com/jsp/jstl/functions"
                template="../../templates/ui.xhtml">

    <ui:define name="head">
        <style type="text/css">
            .ui-confirm-dialog-severity {
                margin: 0 7px 7px 0;
            }      
            .ui-paginator {
                <!--text-align: right ! important -->
            }
            .ui-growl {
                position: absolute;
                right : 38%;               
                top: 1%;                
            }
            .ui-treetable .ui-treetable-data table tr{
                border-style: none;
            }
        </style>
        <script type="text/javascript">
            function handleSearchRequest(xhr, status, args) {
                if (args.validationFailed || !args.found) {
                    jQuery('#modalDialog').effect("shake", {times: 3}, 100);
                } else {
                    searchDialog.hide();
                    jQuery('#').fadeOut();
                }
            }
        </script>  
    </ui:define>

    <ui:define name="content">      

        <div class="entry" >
            <h:form id="form">
                <p:growl id="messages"/> 
                <p:treeTable id="treeTable" value="#{itemCategoryList.root}" var="itemCategory" selectionMode="single" 
                             selection="#{itemCategoryList.selectedNode}" style="border-style: none">

                    <f:facet name="header">
                        <p:toolbar style="width: 100%;border-style: none">  
                            <p:toolbarGroup align="left" >
                                <h1 class="title">Categories</h1>
                            </p:toolbarGroup>                          
                            <p:toolbarGroup align="right" style="padding-top: 1%;" >                       
                                <p:selectOneMenu id="section" 
                                                 value="#{itemCategoryList.purchaseSection}" 
                                                 converter="#{purchaseSectionConverter}" 
                                                 style="width:150px;float: right;">

                                    <f:selectItems value="#{itemCategoryList.purchaseSections}"  
                                                   var="purchaseSection" 
                                                   noSelectionValue="true"
                                                   itemValue="#{purchaseSection}" 
                                                   itemLabel="#{purchaseSection}" />
                                    <p:ajax update="treeTable"  listener="#{itemCategoryList.changeSelectedSection}" /> 
                                </p:selectOneMenu>   
                                <br></br><br></br>
                                <p:commandButton id="newBtn" value="New" icon="ui-icon-document" action="#{itemCategoryList.actionForm}" ajax="false" />
                                <p:commandButton  value="Delete" icon="ui-icon-trash" onclick="confirmDelete.show();" />
                                <p:commandButton  value="Edit" title="Edit" icon="ui-icon-pencil" action="#{itemCategoryList.actionEdit}" update="@(@[id=growl])"/>
                                <p:separator />
                                <p:commandButton value="Search" title="Search" icon="ui-icon-search" oncomplete=""  />
                            </p:toolbarGroup>
                        </p:toolbar>
                    </f:facet>

                    <p:column style="width:80%" >
                        <f:facet name="header" >
                            Name
                        </f:facet>
                        <h:outputText value="#{itemCategory.name}" />
                    </p:column>

                    <p:column style="text-align: center" >
                        <f:facet name="header">
                            Active
                        </f:facet>
                        <h:outputText value="${itemCategory.active ? 'Yes' : 'No'}" />
                    </p:column>

                    <p:column style="width:5%;text-align: center" >
                        <f:facet name="header">
                            Order
                        </f:facet>
                        <h:outputText value="#{itemCategory.orderNumber}" />
                    </p:column>

                    <p:column style="width:5%;text-align: center">
                        <f:facet name="header">
                            Picture
                        </f:facet>
                        <p:graphicImage 
                            id="picture"
                            library="images"
                            name="lec/thumbnails.png"
                            rendered="#{itemCategory.image != null}"
                            >
                        </p:graphicImage>                                             

                        <p:overlayPanel for="picture" showEffect="blind" hideEffect="explode" showEvent="mouseover" hideEvent="mousedown"  
                                        styleClass="ui-helper-clearfix" rendered="#{itemCategory.image != null}">  
                            <p:graphicImage 
                                value="#{itemCategoryList.applicationMediaURL}#{itemCategory.image}" 
                                width="300"  />  
                        </p:overlayPanel>  
                    </p:column>

                    <p:column style="width:5%;text-align: center">
                        <f:facet name="header">
                            Logo
                        </f:facet>
                        <p:graphicImage 
                            id="logo"
                            library="images"
                            name="lec/thumbnails.png"
                            rendered="#{itemCategory.logo != null}"
                            >
                        </p:graphicImage>                                             

                        <p:overlayPanel for="logo" showEffect="blind" hideEffect="explode" showEvent="mouseover" hideEvent="mousedown"  
                                        styleClass="ui-helper-clearfix" rendered="#{itemCategory.logo != null}">  
                            <p:graphicImage 
                                value="#{itemCategoryList.applicationImageURL}#{itemCategory.logo}" 
                                width="300"  />  
                        </p:overlayPanel>                       
                    </p:column>

                    <p:column style="width: 100px;text-align: center">
                        <f:facet name="header">
                            Items
                        </f:facet>
                        <p:commandLink update=":formItem" oncomplete="itemDialog.show();" title="View Items" styleClass="ui-icon ui-icon-search" >
                            <f:setPropertyActionListener value="#{itemCategory}" target="#{itemCategoryList.selectedItemCategory}" />
                        </p:commandLink>
                    </p:column>

                </p:treeTable>

                <p:confirmDialog id="confirmDelete" message="Are you sure about destroying the data ?"  
                                 header="Initiating destroy process" severity="alert" widgetVar="confirmDelete">  

                    <p:commandButton id="confirm" value="Yes" update="@(@[id=growl])" oncomplete="confirmDelete.hide()"  
                                     action="#{itemCategoryList.actionDelete}"  />  
                    <p:commandButton id="decline" value="No" onclick="confirmDelete.hide();" type="button" />   

                </p:confirmDialog>  

            </h:form> 

            <p:dialog id="item" header="Items" widgetVar="itemDialog" modal="true" width="900px" showEffect="clip" hideEffect="clip" > 
                <h:form id="formItem" >                  
                    <p:dataTable  value="#{itemCategoryList.items}" 
                                  var="item"                                       
                                  scrollable="true" 
                                  scrollHeight="350px;" 
                                  >  

                        <p:column style="width:60%;">  
                            <f:facet name="header">  
                                Name
                            </f:facet>  
                            #{item.name}
                        </p:column>

                        <p:column style="width:6%;text-align: center">  
                            <f:facet name="header">  
                                Active
                            </f:facet>  
                            <h:outputText value="${item.active ? 'Yes' : 'No'}"/>
                        </p:column>

                        <p:column style="width:10%;text-align: right;">  
                            <f:facet name="header">  
                                Price
                            </f:facet>  
                            <h:outputText value="#{item.price}">
                                <f:convertNumber type="currency"  currencySymbol=""/> 
                            </h:outputText>
                        </p:column>

                        <p:column style="width:8%;text-align: right">  
                            <f:facet name="header">  
                                Discount
                            </f:facet>                                 
                            <h:outputText value="#{item.discount}">
                                <f:convertNumber type="currency"  currencySymbol=""/> 
                            </h:outputText>
                        </p:column>

                    </p:dataTable> 



                </h:form>  
            </p:dialog> 

        </div>



    </ui:define>
</ui:composition>


pawon-backend/src/main/webapp/ui/master/news_ticker.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                template="../../templates/ui.xhtml"
                xmlns:c="http://java.sun.com/jsp/jstl/core">

    <ui:define name="head">
        <style type="text/css">
            .ui-confirm-dialog-severity {
                margin: 0 7px 7px 0;
            }            
            .ui-paginator {
                <!--text-align: right ! important -->
            }
        </style>
    </ui:define>

    <ui:define name="content">
        <div class="entry" >
            <p:fieldset legend="News Ticker">  
                <p:messages  showDetail="false" autoUpdate="true"  globalOnly="true"/>  
                <h:form id="form" >
                    <p:panel id="panel"  style="width: 100%;border-style: dashed;">

                        <p:panelGrid  style="margin-top:20px;border-style : hidden !important;">                         
                            <p:row> 
                                <p:column style="font-weight: bold;float: left;border-style : hidden !important;">Message</p:column>  
                                <p:column style="width: 90%;">
                                    <p:editor value="#{tickerController.ticker.message}" width="700"/>
                                </p:column>                             
                            </p:row>                                 
                        </p:panelGrid>
                    </p:panel>

                    <p:toolbar style="border-top: none;width: 100%;">  
                        <p:toolbarGroup align="right" style="padding-top: 5px; padding-bottom: 5px;" >
                            <p:commandButton  value="Save" action="#{tickerController.actionSave}" ajax="false" />                         
                        </p:toolbarGroup>
                    </p:toolbar>
                </h:form>
            </p:fieldset>
        </div>
    </ui:define>
</ui:composition>